import type { FieldConfig } from './types'

export const defaultStudentFields: FieldConfig[] = [
    // Basic Information
    {
        id: 'studentName',
        name: 'studentName',
        label: 'Add Student',
        description: 'Student\'s complete name',
        enabled: true,
        position: 1,
        category: 'basic',
        iconName: 'User',
        inputType: 'text'
    },
    {
        id: 'selectedCourse',
        name: 'selectedCourse',
        label: 'Select Course',
        description: 'Course selection dropdown',
        enabled: true,
        position: 2,
        category: 'details',
        iconName: 'GraduationCap',
        inputType: 'select',
        options: [], // Will be populated dynamically from courses database
        searchable: true
    },
    {
        id: 'state',
        name: 'state',
        label: 'Select State',
        description: 'Student\'s state',
        enabled: true,
        position: 2,
        category: 'contact',
        iconName: 'MapPin',
        inputType: 'select',
        options: [
            'Andhra Pradesh',
            'Arunachal Pradesh',
            'Assam',
            'Bihar',
            'Chhattisgarh',
            'Goa',
            'Gujarat',
            'Haryana',
            'Himachal Pradesh',
            'Jharkhand',
            'Karnataka',
            'Kerala',
            'Madhya Pradesh',
            'Maharashtra',
            'Manipur',
            'Meghalaya',
            'Mizoram',
            'Nagaland',
            'Odisha',
            'Punjab',
            'Rajasthan',
            'Sikkim',
            'Tamil Nadu',
            'Telangana',
            'Tripura',
            'Uttar Pradesh',
            'Uttarakhand',
            'West Bengal',
            'Delhi',
            'Jammu and Kashmir',
            'Ladakh',
            'Chandigarh',
            'Dadra and Nagar Haveli and Daman and Diu',
            'Lakshadweep',
            'Puducherry',
            'Andaman and Nicobar Islands'
        ],
        searchable: true
    },
    {
        id: 'studentEmail',
        name: 'studentEmail',
        label: 'Student Email',
        description: 'Student\'s email address',
        enabled: true,
        position: 3,
        category: 'contact',
        iconName: 'User',
        inputType: 'email'
    },
    {
        id: 'phoneNumber',
        name: 'phoneNumber',
        label: 'Phone Number',
        description: 'Student\'s contact number',
        enabled: true,
        position: 4,
        category: 'contact',
        iconName: 'User',
        inputType: 'tel'
    },
    {
        id: 'aadhaarNumber',
        name: 'aadhaarNumber',
        label: 'Adhaar Number',
        description: 'Government issued Aadhaar ID number',
        enabled: true,
        position: 5,
        category: 'basic',
        iconName: 'User',
        inputType: 'text'
    },
    {
        id: 'fatherName',
        name: 'fatherName',
        label: 'Father Name',
        description: 'Student\'s father name',
        enabled: true,
        position: 6,
        category: 'basic',
        iconName: 'User',
        inputType: 'text'
    },
    {
        id: 'motherName',
        name: 'motherName',
        label: 'Mother Name',
        description: 'Student\'s mother name',
        enabled: true,
        position: 7,
        category: 'basic',
        iconName: 'User',
        inputType: 'text'
    },
    {
        id: 'registrationNumber',
        name: 'registrationNumber',
        label: 'Registration Number',
        description: 'Unique student registration ID',
        enabled: true,
        position: 8,
        category: 'details',
        iconName: 'GraduationCap',
        inputType: 'text'
    },
    {
        id: 'city',
        name: 'city',
        label: 'City',
        description: 'Student\'s city',
        enabled: true,
        position: 9,
        category: 'contact',
        iconName: 'MapPin',
        inputType: 'text'
    },
    {
        id: 'dateOfBirth',
        name: 'dateOfBirth',
        label: 'Select Date of Birth',
        description: 'Student\'s birth date',
        enabled: true,
        position: 10,
        category: 'basic',
        iconName: 'Calendar',
        inputType: 'date'
    },
    {
        id: 'admissionDate',
        name: 'admissionDate',
        label: 'Select Admission Date',
        description: 'Date of admission',
        enabled: true,
        position: 12,
        category: 'details',
        iconName: 'Calendar',
        inputType: 'date'
    },
    {
        id: 'maritalStatus',
        name: 'maritalStatus',
        label: 'Select Marital Status',
        description: 'Student\'s marital status',
        enabled: true,
        position: 13,
        category: 'basic',
        iconName: 'User',
        inputType: 'select',
        options: [
            'Single',
            'Married',
            'Divorced',
            'Widowed',
            'Separated'
        ],
        searchable: false
    },
    {
        id: 'address',
        name: 'address',
        label: 'Address',
        description: 'Complete address',
        enabled: true,
        position: 14,
        category: 'contact',
        iconName: 'MapPin',
        inputType: 'textarea'
    },
    {
        id: 'pinCode',
        name: 'pinCode',
        label: 'Pin Code',
        description: 'Postal pin code',
        enabled: true,
        position: 15,
        category: 'contact',
        iconName: 'MapPin',
        inputType: 'text'
    },
    {
        id: 'isActive',
        name: 'isActive',
        label: 'Active Student',
        description: 'Student active status',
        enabled: true,
        position: 16,
        category: 'status',
        iconName: 'UserCheck',
        inputType: 'checkbox'
    },
    {
        id: 'isRegistered',
        name: 'isRegistered',
        label: 'Registered Student',
        description: 'Student registration status',
        enabled: true,
        position: 17,
        category: 'status',
        iconName: 'UserCheck',
        inputType: 'checkbox'
    },
    {
        id: 'completedCourse',
        name: 'completedCourse',
        label: 'Completed Course',
        description: 'Course completion status',
        enabled: true,
        position: 18,
        category: 'status',
        iconName: 'GraduationCap',
        inputType: 'checkbox'
    },
    {
        id: 'studentPhoto',
        name: 'studentPhoto',
        label: 'Student Photo',
        description: 'Upload student photo (JPG, PNG, SVG or GIF - Max 1MB)',
        enabled: true,
        position: 19,
        category: 'basic',
        iconName: 'User',
        inputType: 'file'
    },
    {
        id: 'documents',
        name: 'documents',
        label: 'Documents',
        description: 'Upload student documents (JPG, PNG, SVG or GIF - Max 1MB)',
        enabled: true,
        position: 20,
        category: 'basic',
        iconName: 'User',
        inputType: 'file'
    },
    {
        id: 'signature',
        name: 'signature',
        label: 'Signature',
        description: 'Upload student signature (JPG, PNG, SVG or GIF - Max 1MB)',
        enabled: true,
        position: 21,
        category: 'basic',
        iconName: 'User',
        inputType: 'file'
    }
]

export const defaultCourseFields: FieldConfig[] = [
    {
        id: 'courseName',
        name: 'courseName',
        label: 'Course Name',
        description: 'Name of the course',
        enabled: true,
        position: 1,
        category: 'basic',
        iconName: 'BookOpen',
        inputType: 'text'
    },
    {
        id: 'courseCode',
        name: 'courseCode',
        label: 'Course Code',
        description: 'Unique course identifier',
        enabled: true,
        position: 2,
        category: 'basic',
        iconName: 'BookOpen',
        inputType: 'text'
    },
    {
        id: 'courseDescription',
        name: 'description',
        label: 'Course Description',
        description: 'Detailed course information',
        enabled: true,
        position: 3,
        category: 'details',
        iconName: 'BookOpen',
        inputType: 'textarea'
    },
    {
        id: 'duration',
        name: 'duration',
        label: 'Course Duration',
        description: 'Duration in months',
        enabled: true,
        position: 4,
        category: 'details',
        iconName: 'Calendar',
        inputType: 'number'
    },
    {
        id: 'fees',
        name: 'fees',
        label: 'Course Fees',
        description: 'Total course fees',
        enabled: true,
        position: 5,
        category: 'details',
        iconName: 'BookOpen',
        inputType: 'number'
    },
    {
        id: 'category',
        name: 'category',
        label: 'Course Category',
        description: 'Category of the course',
        enabled: true,
        position: 6,
        category: 'basic',
        iconName: 'BookOpen',
        inputType: 'select',
        options: [], // Will be populated dynamically from course categories
        searchable: true
    },
    {
        id: 'courseImage',
        name: 'courseImage',
        label: 'Course Image',
        description: 'Upload course thumbnail image (JPG, PNG, SVG or GIF - Max 2MB)',
        enabled: true,
        position: 7,
        category: 'details',
        iconName: 'Image',
        inputType: 'file'
    },
    {
        id: 'isActive',
        name: 'isActive',
        label: 'Active Course',
        description: 'Course active status',
        enabled: true,
        position: 8,
        category: 'status',
        iconName: 'UserCheck',
        inputType: 'checkbox',
        defaultValue: true
    }
]

export const defaultBranchFields: FieldConfig[] = [
    {
        id: 'addBranch',
        name: 'addBranch',
        label: 'Add Branch',
        description: 'Branch name or title',
        enabled: true,
        position: 1,
        category: 'basic',
        iconName: 'Building',
        inputType: 'text'
    },
    {
        id: 'userName',
        name: 'userName',
        label: 'User Name',
        description: 'Branch admin username',
        enabled: true,
        position: 2,
        category: 'basic',
        iconName: 'User',
        inputType: 'text'
    },
    {
        id: 'password',
        name: 'password',
        label: 'Password',
        description: 'Branch admin password',
        enabled: true,
        position: 3,
        category: 'basic',
        iconName: 'User',
        inputType: 'text'
    },
    {
        id: 'courseName',
        name: 'courseName',
        label: 'Course Name',
        description: 'Available course at this branch',
        enabled: true,
        position: 4,
        category: 'details',
        iconName: 'GraduationCap',
        inputType: 'text'
    },
    {
        id: 'branchCode',
        name: 'branchCode',
        label: 'Branch Code',
        description: 'Unique branch identifier',
        enabled: true,
        position: 5,
        category: 'basic',
        iconName: 'Building',
        inputType: 'text'
    },
    {
        id: 'email',
        name: 'email',
        label: 'Email',
        description: 'Branch email address',
        enabled: true,
        position: 6,
        category: 'contact',
        iconName: 'User',
        inputType: 'email'
    },
    {
        id: 'phoneNumber',
        name: 'phoneNumber',
        label: 'Phone Number',
        description: 'Branch contact number',
        enabled: true,
        position: 7,
        category: 'contact',
        iconName: 'User',
        inputType: 'tel'
    },
    {
        id: 'directorName',
        name: 'directorName',
        label: 'Director Name',
        description: 'Branch director\'s name',
        enabled: true,
        position: 8,
        category: 'details',
        iconName: 'User',
        inputType: 'text'
    },
    {
        id: 'state',
        name: 'state',
        label: 'Select State',
        description: 'Branch state',
        enabled: true,
        position: 9,
        category: 'contact',
        iconName: 'MapPin',
        inputType: 'select',
        options: [
            'Andhra Pradesh',
            'Arunachal Pradesh',
            'Assam',
            'Bihar',
            'Chhattisgarh',
            'Goa',
            'Gujarat',
            'Haryana',
            'Himachal Pradesh',
            'Jharkhand',
            'Karnataka',
            'Kerala',
            'Madhya Pradesh',
            'Maharashtra',
            'Manipur',
            'Meghalaya',
            'Mizoram',
            'Nagaland',
            'Odisha',
            'Punjab',
            'Rajasthan',
            'Sikkim',
            'Tamil Nadu',
            'Telangana',
            'Tripura',
            'Uttar Pradesh',
            'Uttarakhand',
            'West Bengal',
            'Delhi',
            'Jammu and Kashmir',
            'Ladakh',
            'Chandigarh',
            'Dadra and Nagar Haveli and Daman and Diu',
            'Lakshadweep',
            'Puducherry',
            'Andaman and Nicobar Islands'
        ],
        searchable: true
    },
    {
        id: 'district',
        name: 'district',
        label: 'District',
        description: 'Branch district',
        enabled: true,
        position: 10,
        category: 'contact',
        iconName: 'MapPin',
        inputType: 'text'
    },
    {
        id: 'location',
        name: 'location',
        label: 'Location',
        description: 'Branch location details',
        enabled: true,
        position: 11,
        category: 'contact',
        iconName: 'MapPin',
        inputType: 'text'
    },
    {
        id: 'branchAddress',
        name: 'branchAddress',
        label: 'Branch Address',
        description: 'Complete branch address',
        enabled: true,
        position: 12,
        category: 'contact',
        iconName: 'MapPin',
        inputType: 'textarea'
    },
    {
        id: 'directorAddress',
        name: 'directorAddress',
        label: 'Director Address',
        description: 'Director\'s residential address',
        enabled: true,
        position: 13,
        category: 'contact',
        iconName: 'MapPin',
        inputType: 'textarea'
    },
    {
        id: 'religion',
        name: 'religion',
        label: 'Religion',
        description: 'Religious affiliation if applicable',
        enabled: true,
        position: 14,
        category: 'details',
        iconName: 'User',
        inputType: 'text'
    },
    {
        id: 'branchDocument1',
        name: 'branchDocument1',
        label: 'Branch Document 1',
        description: 'Upload branch document (JPG, PNG, SVG or GIF - Max 1MB)',
        enabled: true,
        position: 15,
        category: 'basic',
        iconName: 'Building',
        inputType: 'file'
    },
    {
        id: 'branchDocument2',
        name: 'branchDocument2',
        label: 'Branch Document 2',
        description: 'Upload additional branch document (JPG, PNG, SVG or GIF - Max 1MB)',
        enabled: true,
        position: 16,
        category: 'basic',
        iconName: 'Building',
        inputType: 'file'
    },
    {
        id: 'fees1',
        name: 'fees1',
        label: 'Enter Fees 1',
        description: 'First fee structure',
        enabled: true,
        position: 17,
        category: 'details',
        iconName: 'BookOpen',
        inputType: 'number'
    },
    {
        id: 'fees2',
        name: 'fees2',
        label: 'Enter Fees 2',
        description: 'Second fee structure',
        enabled: true,
        position: 18,
        category: 'details',
        iconName: 'BookOpen',
        inputType: 'number'
    },
    {
        id: 'fees3',
        name: 'fees3',
        label: 'Enter Fees 3',
        description: 'Third fee structure',
        enabled: true,
        position: 19,
        category: 'details',
        iconName: 'BookOpen',
        inputType: 'number'
    },
    {
        id: 'fees4',
        name: 'fees4',
        label: 'Enter Fees 4',
        description: 'Fourth fee structure',
        enabled: true,
        position: 20,
        category: 'details',
        iconName: 'BookOpen',
        inputType: 'number'
    },
    {
        id: 'fees5',
        name: 'fees5',
        label: 'Enter Fees 5',
        description: 'Fifth fee structure',
        enabled: true,
        position: 21,
        category: 'details',
        iconName: 'BookOpen',
        inputType: 'number'
    },
    {
        id: 'isActive',
        name: 'isActive',
        label: 'Active Branch',
        description: 'Branch active status',
        enabled: true,
        position: 22,
        category: 'status',
        iconName: 'UserCheck',
        inputType: 'checkbox'
    }
]
